Us 2.1.3/baja de usuario
TheAvengersInitiative/ProjectA2Back pull request #29
Opened 2021-09-08 01:07 UTC by TomasBruno1

Como usuario registrado quiero poder eliminar mi usuario para poder eliminar mi participación dentro de la plataforma

UATs:
- El borrado es físico, permitiendo que se registre un nuevo usuario con el email del usuario eliminado o su nickname.

2021-09-08 01:41 UTC, AlbertoPizzi approved these changes

2021-09-10 12:10 UTC, agusayerza requested changes

2021-09-10 12:10 UTC, agusayerza commented on src/main/java/com/a2/backend/service/impl/UserServiceImpl.java
> +        if (!userRepository.existsById(id))
Anyone can delete any user?

2021-09-10 12:12 UTC, agusayerza commented
Let's wait for Login Logout feature to be implemented so we can verify who is requesting the delete

2021-09-14 23:17 UTC, agusayerza approved these changes

2021-09-14 23:19 UTC, merged