Us 6.1.1.2/prefered projects list
TheAvengersInitiative/ProjectA2Back pull request #58
Opened 2021-09-28 03:03 UTC by AlbertoPizzi

Como usuario quiero ver en la landing page los proyectos que me interesan para poder accederlos rápidamente.
UATs:

- Se deben mostrar 6 proyectos (4 de preferencias y 2 de featured)
- Los featured projects ignoran las preferencias y son elegidos al azar de la lista de featured projects
- Si no hay suficientes proyectos con las preferencias solicitadas se rellenan los proyectos faltantes con proyectos elegidos al azar.

Los featured projects son aquellos que se cargan en el demo runner, el resto de los proyectos son no-featured

2021-09-28 19:36 UTC, manumasjoan approved these changes

2021-09-29 01:55 UTC, fabriziodisanto requested changes
Un cambio menor, el resto todo bien

2021-09-29 01:55 UTC, fabriziodisanto commented on src/main/java/com/a2/backend/controller/UserController.java
> +    }
En vez de List<Project> conviene devolver List<ProjectDto>

2021-09-30 01:57 UTC, fabriziodisanto approved these changes
Fijate despues de en el projectDTO cambiar el User por UserDTO

2021-09-30 01:57 UTC, merged