Us 4.1.3/calificacion de colaboradores
TheAvengersInitiative/ProjectA2Back pull request #68
Opened 2021-10-07 23:12 UTC by manumasjoan

Como usuario dueño de proyecto quiero poder calificar a los colaboradores del proyecto tal que se actualice su valor de reputación

Desde la vista de administración de proyecto en la tab de colaboradores del proyecto se debe poder calificar a cada uno de los colaboradores
Cuando se lo va a calificar se completa un pop up que tiene un puntaje del 1 al 5. La calificación mínima es un 1.
El comentario debe ser opcional y debe tener un máximo de 500 caracteres
Una vez que la calificación se realizó se debe mostrar un mensaje que diga que fue realizada exitosamente
Si falla debe aparecer un mensaje
Se debe poder ver el historial de calificaciones realizadas para cada usuario. Esto debe verse como un pop up de la pantalla de colaboradores del proyecto (Para cada proyecto, poder pedir una lista que contenga los datos: user, fecha, comentario y califacion). Esto solo lo puede ver el owner de un proyecto.
Cada calificación tiene una fecha en la que fue realizada, el puntaje asignado y el comentario si este existe para esa calificación en particular

2021-10-07 23:34 UTC, AlbertoPizzi approved these changes
LGTM

2021-10-08 19:02 UTC, TomasBruno1 requested changes
Two minor changes

2021-10-08 19:02 UTC, TomasBruno1 commented on src/main/java/com/a2/backend/entity/Review.java
> +    private String comment;
Missing annotation `@Column(length=500)` (see Bug US 2.1.2)

2021-10-08 19:02 UTC, TomasBruno1 commented on src/main/java/com/a2/backend/service/impl/ProjectServiceImpl.java
> +                .filter(r -> r.getCollaborator().getId() == userId)
nice

2021-10-08 19:02 UTC, TomasBruno1 commented on src/test/java/com/a2/backend/service/impl/ReviewServiceImplTest.java
> +class ReviewServiceImplTest extends AbstractServiceTest {
We should rename this to something like `ReviewSerciveActiveTest` since it uses DemoRunner

2021-10-08 19:51 UTC, TomasBruno1 approved these changes

2021-10-08 19:54 UTC, merged